### ISSUE TITLE
Gradle: not installed

### ISSUE THREAD

**Issue by hanilozmen** [apache/cordova#158]
I have Android Studio and SDK and I am able to run Android apps. However, when I run the command "cordova requirements" after running "cordova create testapp com.hanilozmen.testcordova TestApp", I am always getting this error, even I downloaded gradle manually and added it to the Path as 'C:\Gradle\gradle-5.1.1\bin':

Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-28,android-27,android-26,android-24,android-23,android-22,android-21,android-16,Google Inc.:Google APIs:16,android-15,Google Inc.:Google APIs:15
Gradle: not installed
Cannot read property 'length' of undefined
Some of requirements check failed

---------------------
What would be the reason for this error? Other settings:

OS: Windows 10
npm : 6.11.3
nodejs: 10.16.3
Gradle 5.1.1

I also added required environment parameters: 
ANDROID HOME -> C:\AndroidSDK
ANDROID_SDK_ROOT -> C:\AndroidSDK
JAVA_HOME -> C:\Program Files\Java\jdk1.8.0_191
JRE_HOME -> C:\Program Files\Java\jre1.8.0_201

Also, these are in the 'Path' : 
C:\AndroidSDK\tools\bin
C:\AndroidSDK\tools
C:\AndroidSDK\platform-tools\bin
C:\AndroidSDK\platform-tools
C:\Gradle\gradle-5.1.1\bin

**Comment by hanilozmen** [comment]
Somehow, cordova searches gradle under ProgramFiles/Android/AndroidStudio folder. I changed the folder name from AndroidStudio to AndroidStudio1 and the issue is solved. It is an ugly way, but works.

**Comment by joserogeriofilho** [comment]
Had a similar problem due to the same cause: on Windows, my Android Studio was not installed on the default folder "ProgramFiles" (it was even on a different disk partition than my OS).

The error I got was "Cannot read property 'toString' of null" and I solved it by forcing to always get my external gradle installation instead of looking for the one embedded on Android Studio on ``check_reqs.js``:

``module.exports.get_gradle_wrapper = function () {
    return forgivingWhichSync('gradle');
}``

Renaming the Android Studio folder did not work for me.
