### ISSUE TITLE
Version pinning in Cordova CLI (via cordova-lib)

### ISSUE THREAD

**Issue by janpio** [apache/cordova#18]
In https://github.com/apache/cordova-lib/blob/master/src/platforms/platformsConfig.json Cordova "pins" a number of platforms to a specific version, that is used to install the platform is no other version is supplied. This behavior is also mentioned in several places in https://github.com/apache/cordova-coho/blob/master/docs/versioning-and-release-strategy.md.

The clear disadvantage of this behavior is that we need to do a release of `cordova-lib` (and `cordova-cli` that contains it) to update the pinned versions. Until then, people just running e.g. `cordova platform add android` will get an outdated version by default and (from experience on Stack Overflow, Ionic Forum and `support` issues here) have to be told regularly to update the platform when they encounter a bug (`cordova platform add android@7.1.1`) - it is just not really expected behavior for most users that the default command doesn't install the newest version.

1. Why do we need pinned versions?
1. What is the history behind this feature?
1. What are the advantages of it?
1. Does this behavior still make sense today?
1. Can we maybe get rid of it and replace it with "will install `latest` by default, but can of course still be overridden by supplying a specific version" in a future cli/lib version?

**Comment by oliversalzburg** [comment]
I guess the idea is that when you install an old version of Cordova, you get platform versions that are compatible with it, instead of the incompatible, latest version.

**Comment by janpio** [comment]
That might be have been a motivation.  
Is there no other mechanism to select a platform that actually works with the CLI version (or other way around: For a platform to require a Cordova CLI / cordova-lib version)?
Even then, is this worth the added hassle?

**Comment by oliversalzburg** [comment]
In general, I'm not opposed to the mindset that you get a "proven working" combination of modules with whatever version of Cordova you're using and then updating those modules as desired.

I imagine this is similar to downloading an installer for a desktop application, which then installs an update right after the initial installation.

From your initial assessment, I would conclude that the actual issue is that the user will not realize that newer packages may be available. I would suggest leaving the version pinning in place and instead add update checks as applicable. Maybe along the lines of https://github.com/yeoman/update-notifier

If that's not acceptable, I would prefer dropping version pinning and putting emphasis on the latest versions of the modules. The old versions of platforms and other modules are losing importance constantly, because technologies are deprecated and removed all the time. I don't even know what I could do today with a 2 year old Cordova version; pinned versions or not. So providing users with the best code possible (which should be the latest) should be preferred.

**Comment by janpio** [comment]
That's exactly where my thoughts come from: You would have to upgrade everything to make it work with modern iOS and Android.

**Comment by brodybits** [comment]
> In https://github.com/apache/cordova-lib/blob/master/src/platforms/platformsConfig.json
> Cordova "pins"
> [...]

to a specific major/minor version using the `~` (tilde) character, which would still match if a patch is made on the same major/minor version.

I *think* some of the `semver` rules and features would apply if used by the user, would have to investigate and test to say for sure.

> 4\. Does this behavior still make sense today?

I think so.

Definitely should not use higher major version of a platform unless explicitly requested by user.

It *should* also be possible for Cordova to the platform to specific major only by using `^` (caret). I would personally not favor this by default.

**Comment by brodybits** [comment]
> I would suggest leaving the version pinning in place and instead add update checks as applicable. Maybe along the lines of https://github.com/yeoman/update-notifier

👍

> If that's not acceptable, I would prefer dropping version pinning and putting emphasis on the latest versions of the modules.

👎

**Comment by brodybits** [comment]
> Do you mean "major or minor" or "major+minor" here?

MAJOR+MINOR, just updated the comment above

> > I think some of the `semver` rules and features would apply if used by the user
> > [...]
> 
> What "user" are you referring to here?

Cordova CLI user

**Comment by oliversalzburg** [comment]
> While I don't disagree, doesn't this "just" apply to the CLI itself (at least by common use of the tool) and not the platforms installed?

I think you're right. I have not used that particular module in my own code. I just picked it as an illustration of what I had in mind: A non-intrusive way to notify the user about new versions.

**Comment by janpio** [comment]
>>> I think some of the semver rules and features would apply if used by the user
>>> [...]
>>
>> What "user" are you referring to here?
>
> Cordova CLI user

That might as well be, but is not relevant regarding the version pinning (meaning: default version installed when _no_ version is specified by the user, no exact version and no semver anything). Or did I misunderstand?

**Comment by brodybits** [comment]
> The user just runs `cordova platform add android` and expects to get the latest and greatest.

I think "latest" should have been written with back-ticks (`latest`) since `latest` tag on npm generally means latest stable release (my understanding, at least).

If the Cordova CLI user would do `cordova platform add android@latest`, for example, then the Cordova CLI does the following (just tested with `cordova@8.0.0` package version):
* fetch `cordova-android@latest` from npm
* add `<engine name="android" spec="latest" />` to `config.xml` (this will go away in next major Cordova release)
* add `"cordova-android": "^7.1.1"` entry to `package.json`

I am coming around to favor that this should be the case by default, if the Cordova CLI user runs `cordova platform add android` for example. But this means that we better ensure that newer major release of Cordova platform packages will work with older major release of Cordova CLI, to a reasonable extent at least.

**Comment by janpio** [comment]
I actually really meant "latest and greatest" above, not any deeper specific meaning.
But: "latest and greatest" probably is `latest` on npm, so you are correct 👍 

> But this means that we better ensure that newer major release of Cordova platform packages will work with older major release of Cordova CLI, to a reasonable extent at least.

That of course is an absolute requirement, including the ability to config a platform release to only be installed in CLI versions it works with (meaning e.g. ">12.0.0" or similar if that new platform only works with CLI 12 and newer because we changed something there).

**Comment by raphinesse** [comment]
@janpio What you describe in your last comment would usually be handled using `peerDependencies`. In this approach, a platform would specify that it needs one of a certain range of Cordova versions to be installed alongside it to work properly.

The problem here is that we recommend users to install tooling globally while platforms are installed locally. Moreover, we seem to support more than one workflow where platforms are used without `cordova-lib` (platform-centric with `plugman`, using only platforms and their scripts, ...)

**Comment by janpio** [comment]
> What you describe in your last comment would usually be handled using peerDependencies. In this approach, a platform would specify that it needs one of a certain range of Cordova versions to be installed alongside it to work properly.

Does this already work? Does this make sure, a platform requiring a newer "interface" doesn't get installed with older CLIs?

> The problem here is that we recommend users to install tooling globally while platforms are installed locally. Moreover, we seem to support more than one workflow where platforms are used without cordova-lib (platform-centric with plugman, using only platforms and their scripts, ...)

Ok, so does this answer the question I posed in my original post? Do we need the pinning because of that?

**Comment by raphinesse** [comment]
For the record: `cordova-lib@9` had relaxed the version pinning from `~` to `^` so as to allow minor updates of platforms to be propagated without publishing an update to the library.
