### ISSUE TITLE
V8 Heap Snapshot for android - protects the javascript code

### ISSUE THREAD

**Issue by onelsonic** [apache/cordova#204]
Hi there,
please correct me if I am wrong.

On android Cordova is using the V8 JavaScript Engine?
So theoretically we should be able to enable the use of V8 Heap Snapshot in Cordova for Android?
With this we should be able to protect the Javascript Source code of the App created, and also speed up the execution of the Javascript Code, thus improving the performances of Cordova on Android.

I haven't found anything about this for Cordova.
V8 Snapshots : 
https://v8.dev/blog/custom-startup-snapshots

The same technique is use in Atom and NW.js.
https://flight-manual.atom.io/behind-atom/sections/how-atom-uses-chromium-snapshots/
https://nwjs.readthedocs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/

**Comment by breautek** [comment]
Cordova doesn't interface with V8 at all. It simply just interfaces with a webview (which happens to be chrome on android). And even then, we don't have direct access. Cordova only access to the java apis documented at https://developer.android.com/reference/android/webkit/WebView

Not sure how it would be possible to get what you want (that would be a research project in itself), but I think it would involve bundling native libraries, and having a plugin that exposes native c methods to java (via jni) and having a Cordova plugin that handles the javascript to java api calls.

I'm closing the issue because this is not something Cordova will support. It is more appropriate as a third party plugin. We do welcome further discussion on our [slack](http://slack.cordova.io/)

**Comment by onelsonic** [comment]
ok thanks for your feedback, I will digg this around.
