### ISSUE TITLE
IOS Device Http Post Not working

### ISSUE THREAD

**Issue by bevinGithub** [apache/cordova#232]
Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by bevinGithub** [comment]
I  have done an app with ionic 4 and on he browser is working but on the device its not working. Unknow error, which has to do with cors issue. I tried to install Http Native and its also not working splash screen and hangs on the white screen.

How can l configure the CORS issue

**Comment by breautek** [comment]
If you're using XHR to load in local content (which is common with some frameworks like angular), then you must use cordova-ios@6 and schemes.

If for some reason you cannot upgrade to cordova-ios@6, then [cordova-plugin-wkwebview-file-xhr](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr) will workaround the issue for local file requests (ie your `file://` xhr requests).

https://cordova.apache.org/howto/2020/07/18/uiwebview-warning.html

If you're trying to communicate with an external server, that server must implement a CORS policy to allow your app. The origin of your app will be `null` if you're using the `file://` protocol or whatever what your scheme setting is, e.g: `app://localhost`.

I do have a [blog post](https://breautek.com/2020/07/14/enabling-cors/) that goes into more detail on how to enable CORS on your server.

Because this isn't a bug or a feature request I'll be closing this ticket. A more suitable place for support is on our [slack](http://slack.cordova.io/).
