### ISSUE TITLE
Google Analytics for Cordova App

### ISSUE THREAD

**Issue by PhilippMatzel** [apache/cordova#281]
Dear all,

i am using Cordova to deploy my Angular app on iOS and Android devices. Additional the app is available on a open website. To track user activity i want to use Google Analytics and here comes my question: Is it enough to just use web as datastream? Or do i need to add additional code to track my "web app" when its open as iOS or Android app?

**Comment by breautek** [comment]
For support, please ask in our [Slack](http://slack.cordova.io/) community, or in [StackOverflow](https://stackoverflow.com/questions/tagged/cordova)

To answer your question however...

Most Google APIs intended to be consumed by web applications are assumed to ran from a webserver and are often tied to a domain. This is a problem for Cordova apps as they are domain-less since the application is not hosted on a webserver, but the device itself.

Most Google APIs intended to be consumed by mobile applications often have tools to restrict API usage to the application/bundle id and this is the proper way to consume such libraries. You'll need to find (or write) a cordova plugin that interfaces with the native libraries however.

**Comment by PhilippMatzel** [comment]
Thanks a lot for your reply, next time i will write in Slack or StackOverflow.

I found a suitable plugin:

https://www.npmjs.com/package/cordova-plugin-google-analytics
