### ISSUE TITLE
HarmonyOS Platform support

### ISSUE THREAD

**Issue by dongasai** [apache/cordova#290]
# Feature Request

Be able to build HarmonyOS (HPK)

## Motivation Behind Feature

Harmonyos is a new operating system.

**Comment by NiklasMerz** [comment]
Random thoughts: Doesn't Harmony OS run Android Apps? What does a new platform offer over using the Android platform?

**Comment by breautek** [comment]
> Random thoughts: Doesn't Harmony OS run Android Apps? What does a new platform offer over using the Android platform?

Not 100% sure but I believe Harmony OS is a fork of the AOSP, so it can run android apps, but HarmonyOS doesn't have any google play APIs enabled, so any apps that depends on Google Play services or any of the google libraries for Location, Maps, etc... won't run properly on HarmonyOS.

I don't know if any of our codebase depends on any Google libraries, but it might be hard for plugin authors to optionally include plugin dependencies depending if the platform is going to be ran on Google android variant or Harmony.

**Comment by dongasai** [comment]
I don't think I have the right description of the requirements, which can be packaged as a harmony format (HPK), rather than packaging out the installation package (APK) that can run in harmony

**Comment by dongasai** [comment]
As a hydration application developer, my idea is that I don’t care about the realization of the system. What I care about is whether I can package an installation package that meets the system specifications, that is, Linux can run exe through wine, but exe cannot be used in the Linux market The best format for promotion

**Comment by breautek** [comment]
My best advice on this is to probably build a new cordova platform for harmony. I think it will likely be difficult to support both android and harmony without causing breakage to one environment or another which is why a separate platform I think would be best.

To solve plugin support issue, it can do something similar to what the electron platform did, which is to find/use electron implementations first and fallback to a browser implementation of the plugin. For this new Harmony platform, I imagine most "android" plugins would work as-is on HarmonyOS but this allows plugin developers to provide a harmony OS alternative implementation of their plugin if necessary.

Unfortunately the Apache Cordova project only has a few dedicated members that are active and most of our volunteer time is being spent on maintaining existing Cordova tooling and platforms. Therefore unless if one of our current members have a requirement of supporting HarmonyOS, I don't expect much movement on Apache's side. We've been working on reducing our maintenance load by deprecating platforms. This doesn't mean our community won't support efforts on building a solution for Harmony. If you have any questions, our community [Slack](http://slack.cordova.io/) channel is a great place to ask.

**Comment by jcesarmobile** [comment]
I’m closing the issue as breautek has already explained the situation.
We are low in resources and can’t maintain a new platform with low usage, but anybody from the community can create a 3rd party platform and maintain it, and in the future if the usage of harmonyOS increases they could donate the platform to Apache (if the maintainers from both sides are interested)

**Comment by wkwarren** [comment]
cordova HarmonyOS
https://ohpm.openharmony.cn/#/en/detail/harmony-cordova
