### ISSUE TITLE
Android 11 support

### ISSUE THREAD

**Issue by tushaagit** [apache/cordova#337]
# Feature Request
cordova Android 11 and 12 support expected release date?

**Comment by breautek** [comment]
API 31 & 32 will be supported in our next major release.

Due to volunteer nature of Apache projects, I cannot give a timeline, but the release actively progressing through the Apache's release process, so I can say it will be released soon.

**Comment by erisu** [comment]
[Cordova-Android@11.0.0](https://www.npmjs.com/package/cordova-android/v/11.0.0) has already been released and the [Android API Level Support](https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#android-api-level-support) table can be read here.

**Comment by xecomit** [comment]
The latest android platform that [Cordova-Android@11.0.0] supports is android 10.1.2,  We have few third party plugins like background geolocation which requires to upgrade the sdk version to latest i.e 32 which is currently not possible due to older android platform and API's, Please recommend any good background geo tracking plugin which can provide good support to existing cordova platform
![image](https://user-images.githubusercontent.com/53864965/182612594-e9f4c42b-a25e-4a59-83d0-592b619b1a3e.png)

**Comment by breautek** [comment]
> The latest android platform that [Cordova-Android@11.0.0] supports is android 10.1.2

This statement doesn't make a whole lot of sense. android 10.1.2 as shown in your installed platforms is the installed cordova-android version. You can upgrade it by running these commands:

```
cordova platform remove android
cordova platform add android@11
```

Which will install the latest release of cordova-android@11.

cordova-android@11 supports API 31 and 32. By default it will target API 32.

Locking this thread to avoid further hijacking. If you have further questions, I'd suggest asking our [Slack Community](https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q)
