### ISSUE TITLE
Where are the plugins?

### ISSUE THREAD

**Issue by tellts** [apache/cordova#339]
The page does not show any plugins. https://cordova.apache.org/plugins/

**Comment by breautek** [comment]
The underlying third-party web service is offline. For the time being you can search plugins via NPM directly using the keyword `ecosystem:cordova` filter: https://www.npmjs.com/search?q=keywords:ecosystem:cordova

This issue is being tracked at https://github.com/apache/cordova-docs/issues/1128

Closing as duplicate.
