### ISSUE TITLE
Soft keyboard disappearing in Android app

### ISSUE THREAD

**Issue by PedroRF123154** [apache/cordova#499]
# Bug Report

## Problem
Soft keyboard disappearing in Android app

I have this problem with many users, I found a page about this and I tried several published functions but the problem persists.

https://stackoverflow.com/questions/38296574/disappearing-soft-keyboard-in-android-app

### What is expected to happen?

Any solution for this?

### What does actually happen?

Soft keyboard disappearing in Android app

### Environment, Platform, Device

https://stackoverflow.com/questions/38296574/disappearing-soft-keyboard-in-android-app
![w6X1l](https://github.com/user-attachments/assets/b52629d3-0203-42d2-a676-af5219840b1a)

What are relevant versions you are using?
Platform Android
Cordova Android 13.0.0
"org.apache.cordova.batterystatus.BatteryListene
org.apache.cordova.camera.CameraLauncher
org.apache.cordova.device.Device
org.apache.cordova.dialogs.Notification
org.apache.cordova.file.FileUtils
org.apache.cordova.geolocation.Geolocation
org.apache.cordova.inappbrowser.InAppBrowser
org.apache.cordova.networkinformation.NetworkManager
org.apache.cordova.media.AudioHandler
cordova.plugins.screenorientation.CDVOrientation
org.apache.cordova.statusbar.StatusBar
com.adobe.phonegap.push.PushPlugin
by.chemerisuk.cordova.AppReviewPlugin
com.butterflyeffect.plugins.GPSDetectionPlugin
uk.co.whiteoctober.cordova.AppVersion
"com.plugin.datepicker.DatePickerPlugin
org.apache.cordova.filetransfer.FileTransfer
nl.xservices.plugins.Insomnia
net.justin_credible.cordova.SpinnerPlugin
io.sqlc.SQLitePlugin
com.phonegap.plugins.barcodescanner.BarcodeScanner
nl.codeyellow.plugin.SignaturePlugin
com.phonegap.plugin.mobileaccessibility.MobileAccessibility

Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
I'm closing this issue because it seems unlikely that this is framework issue. A better place to for support questions is on the [GitHub Discussions](https://github.com/apache/cordova/discussions) page. I see that you've already opened a discussion at https://github.com/apache/cordova/discussions/498 so if you're still experiencing the issue, then the discussion can be reopened.

If the discussion finds more details surrounding the problem that shows it is a problem within Cordova framework then we can open an issue accordingly with the new details found.

**Comment by PedroRF123154** [comment]
Thanks
