### ISSUE TITLE
androidx support

### ISSUE THREAD

**Issue by brodybits** [apache/cordova#69]
From discussion in apache/cordova-android#565 I think that `androidx` is not supported properly and needs to be improved. Described in a number of places including:
- <https://stackoverflow.com/questions/51280090/what-is-androidx>
- <https://developer.android.com/jetpack/androidx/> (with important info in <https://developer.android.com/jetpack/androidx/migrate>)
- <https://android-developers.googleblog.com/2018/05/hello-world-androidx.html>

In short: `androidx` Java packages replace use of `android` Java packages for "unbundled" Java packages, meaning part of the SDK and not part of the Android system libraries. Use of old "unbundled" Java packages seems to be deprecated, obsolete.

I tried to explain in apache/cordova-android#565 that this should not be an issue with the Cordova Android platform itself. I think we will have to update at least some of the plugins, though.

I am flagging this as a bug at the top level due to usability issues that I think have started to come to light in apache/cordova-android#565, especially with the PSPDFKit.

I would *personally* like to see this resolved before we finish the Cordova 9 release (#10). This is my personal opinion for the sake of usability and not to be interpreted as the official position of Apache Cordova.

**Comment by dpogue** [comment]
> I would personally like to see this resolved before we finish the Cordova 9 release (#10).

Correct me if we've discovered otherwise, but I believe there is nothing to resolve **at the cordova-android level**, and therefore nothing that would delay Cordova 9. The changes for Android X need to happen in new major versions of the plugins, which is beyond the scope of the Cordova 9 release.

**Comment by jcesarmobile** [comment]
Well, I did a quick read and it looks like it just needs to target SDK 28, which I think it's already there. (I noticed this file still uses 27, but not sure if it's used anymore https://github.com/apache/cordova-android/blob/master/framework/project.properties#L13)

And set two values to true in a `gradle.properties` file, which I can't find on Cordova projects, so not sure if we want to create it as default or leave the users do it themselves (probably not as it should go in projectName/platforms/android/ and everything there will be wiped).

Also we should try and see what happens when some plugins use the new "support library", and others the old one

**Comment by brodybits** [comment]
> (I noticed this file still references 27, but not sure if it's used anymore https://github.com/apache/cordova-android/blob/master/framework/project.properties#L13)

I think that needs to be updated, will raise a PR with a better explanation.

**Comment by dpa99c** [comment]
> The changes for Android X need to happen in new major versions of the plugins, which is beyond the scope of the Cordova 9 release.

@dpogue I think this presents a problem for plugin authors such as myself since it is up to the Cordova project owner/plugin user as to whether they optionally enable AndroidX by manually adding the required properties to `gradle.properties` (see https://github.com/dpa99c/cordova-diagnostic-plugin/issues/350).

A reason they may choose not to enable AndroidX is that other 3rd-party Cordova plugins on which their project depends have not been updated for AndroidX - many popular 3rd party plugins are poorly maintained.

Therefore a new major plugin version that is updated for AndroidX will be ununsable in projects which have not been configured to use AndroidX: I can foresee a flood of issues opened against my plugins along the lines of "AndroidX support broke my Cordova Android builds". 

If the next major version of `cordova-android` configured AndroidX to be enabled by default, this would be less of an issue because plugin authors could use `<engines>` in the `plugin.xml` to restrict the new major plugin version to a minimum of that latest version of `cordova-android`.

In the meantime, I'm considering whether I can create a hook script which runs on plugin installation and depends on a plugin variable (i.e. `ANDROIDX_ENABLED=true|false`) which would dynamically replace the relevant class names in the Java source code and the `<framework>` elements in the `plugin.xml`.
This would enable a single version of my plugins to run both with or without AndroidX.

**Comment by dpa99c** [comment]
I've implemented a generic solution for AndroidX support in my plugins which reference the Android Support Library by creating a couple of new plugins:

- [cordova-plugin-androidx](https://github.com/dpa99c/cordova-plugin-androidx) will persistently configure a Cordova Android platform project to use AndroidX.
- [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) migrates any references to the legacy Support Library in a Cordova Android platform project to use the AndroidX equivalent names.

This means that by installing both of these plugins in a Cordova project that already contains plugins which reference either the legacy Support Library names and/or the AndroidX names, the build will now succeed.

For example, try this test case:

	cordova create test && cd test
	cordova platform add android@8
	cordova build android
		=> build succeeds
	cordova plugin add cordova.plugins.diagnostic
	cordova build android
		=> build succeeds
	cordova plugin add cordova-plugin-androidx
	cordova build android
		=> build fails
	cordova plugin add cordova-plugin-androidx-adapter
	cordova build android
		=> build succeeds

**Comment by jcesarmobile** [comment]
wow, this is amazing, thanks @dpa99c!

**Comment by wf9a5m75** [comment]
Since the some users of my plugin use `PhoneGap Build` which does not support `hook scripts`, @dpa99c 's solution does not work. (And they always report to me)

I think most cloud build services do not support cordova hook scripts due to the security reason.

**Comment by jcesarmobile** [comment]
As far as I know only Phonegap Build doesn't support hooks.

The Android X support is ready, we just need to release cordova-android 9

But doesn't look like Phonegap Build is doing more updates in their servers, so the cordova-android 9 release won't help you. Check the adobe forums and you'll see dozens of topics about the iOS 13 SDK requirements not met by Phonegap Build and no official answer.

**Comment by wf9a5m75** [comment]
As we discuss `cordova-plugin-androidx-adapter` does not work on PhoneGap build.
It means this solution is not perfect for me.

That's why I re-created another plugin, which is written in `gradle` script.
[cordova-androidx-build](https://github.com/wf9a5m75/cordova-androidx-build)

The purpose of this plugin is little different from `cordova-plugin-androidx-adapter`.
`cordova-plugin-androidx-adapter` migrates the project code from `Android Support Libraries` to `AndroidX libraries`, which is one way.
This is OK for general developers. However plugin developers have to support both environments for a while (`Cordova 8` and `Cordova 9`).

That's why this plugin migrates from `AndroidX libraries` to `Android Support Libraries` if the environment does not support `AndroidX`.

![work-flow](https://user-images.githubusercontent.com/167831/83340259-c2773400-a28a-11ea-8bb5-56d4a1a170fe.png)

And this plugin uses `Gradle` script, works on PC and cloud services.

**Comment by almothafar** [comment]
@wf9a5m75 sadly, it is not working:

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.appcompat:appcompat:1.1.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.versionedparcelable:versionedparcelable:1.1.0, androidx.fragment:fragment:1.1.0, an
droidx.core:core:1.2.0, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.constraintlayout:constraintlayout-solver:1.1.3, androidx.interpolator:interpolator:1.0.0, androidx.loader:l
oader:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.activity:activity:1.0.0, androidx.collection:collection:1.1.0, androidx.viewpager:viewpager:1.0.0, androidx.cardview:cardview:1.0.0, androidx.localbroadcastmanager:loca
lbroadcastmanager:1.0.0, androidx.arch.core:core-common:2.1.0, androidx.savedstate:savedstate:1.0.0, androidx.annotation:annotation:1.1.0, androidx.lifecycle:lifecycle-common:2.1.0, androidx.appcompat:appcompat-resources:1.1.0, andr
oidx.lifecycle:lifecycle-livedata:2.0.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.lifecycle:lifecycle-viewmodel:2.1.0, androidx.constraintlayout:constraintlayout:1.1.3, androidx.lifecycle:lifecycle-livedata-core:2.0.0,
 androidx.browser:browser:1.0.0, androidx.legacy:legacy-support-v4:1.0.0, androidx.media:media:1.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0,
androidx.cursoradapter:cursoradapter:1.0.0, androidx.vectordrawable:vectordrawable-animated:1.1.0, androidx.lifecycle:lifecycle-runtime:2.1.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclay
outinflater:1.0.0, androidx.vectordrawable:vectordrawable:1.1.0, androidx.print:print:1.0.0


```

Still getting this.

**Comment by dpa99c** [comment]
@almothafar have you set the preference in `config.xml` as outlined in the [`cordova-android@9.0.0` release annnouncement](https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html)?

    <preference name="AndroidXEnabled" value="true" />

**Comment by dpa99c** [comment]
BTW @brodybits can this be closed as `cordova-android@9` now supports AndroidX?

**Comment by jcesarmobile** [comment]
Yeah, closing since AndroidX is now supported.

There are some ongoing conversations about making the platform androidX only for next release or as an independent platform on [this issue ](https://github.com/apache/cordova-android/issues/841)

It was also mentioned on an online meetup we did a few weeks ago [see recording](https://www.youtube.com/watch?v=oarY6ZYj-CU)

**Comment by almothafar** [comment]
@dpa99c oh my bad, I totally forgot that, do I need to install "cordova-androidx-build" as well? or not necessary?
